initial_memories:
  - summary: "Dremig喜欢吃的东西包括牛肉和禽肉，他也很喜欢吃青菜，包括香菜"
    keywords: ["Dremig", "牛肉", "禽肉", "青菜", "香菜"]
  - summary: "Dremig喜欢吃辣的食物，但是他的口味除了辣之外其实偏清淡"
    keywords: ["Dremig", "辣", "清淡"]
  - summary: "Dremig喜欢吃甜食和冰的东西，比如蛋挞和冰淇淋"
    keywords: ["Dremig", "甜食", "蛋挞", "冰淇淋"]
  - summary: "Dremig喜欢看动漫，尤其是恋爱轻喜剧"
    keywords: ["Dremig", "动漫", "恋爱轻喜剧"]
  - summary: "Dremig喜欢听音乐，也喜欢听虚拟歌姬"
    keywords: ["Dremig", "音乐", "虚拟歌姬"]
  - summary: "Dremig比较喜欢玩fps类的游戏"
    keywords: ["Dremig", "FPS", "游戏"]
  - summary: "Dremig最近才开始健身，每天都跑3-5公里"
    keywords: ["Dremig", "健身", "跑步"]
  - summary: "Dremig现在在玉泉校区上课"
    keywords: ["Dremig", "玉泉校区", "上课"]
  - summary: "叶阑非常喜欢喝咖啡，尤其是拿铁"
    keywords: ["叶阑", "咖啡", "拿铁"]
  - summary: "叶阑正在学习日语，每天都会花一些时间练习"
    keywords: ["叶阑", "日语", "学习"]
  - summary: "叶阑最近迷上了看科幻电影，最喜欢的电影是《星际穿越》"
    keywords: ["叶阑", "科幻电影", "星际穿越"]
  - summary: "叶阑在前段时间工作中负责前端开发，最近正在使用 React 和 Vue 框架"
    keywords: ["叶阑", "前端开发", "React", "Vue"]
  - summary: "叶阑喜欢吃辣，特别是麻辣火锅"
    keywords: ["叶阑", "辣", "麻辣火锅"]
  - summary: "叶阑擅长 CTF 网络安全竞赛,曾获得过许多奖项"
    keywords: ["叶阑", "CTF", "网络安全竞赛"]
